from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace, HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
from langchain_community.vectorstores import FAISS
from dotenv import load_dotenv


load_dotenv()

text = """
Deepfakes, or the synthetic media generated by artificial intelligence, pose a significant threat to the authenticity of the information. The fake visual data available 
on social media poses a significant threat to the users associated with it. In this review, we look into the usage of Generative Adversarial Networks (GANs) for the detection of 
generated content known as deepfakes. Further, we will understand the mathematical functioning of GANs along with the different architectures like cGANs, DCGANs, StarGANs, 
and StyleGANs. The detection of these deepfakes has been around for a while, so some detection methods are available; we will explore those as well. To check how well a method 
works in detecting the deepfake, we have some evaluation metrics, broadly categorised as quantitative and qualitative measures. This review provides a complete overview of the 
GAN-based approaches used for deepfake detection of the visual content.

The generated content, or the deepfake, is the by-product of the artificial intelligence model where one person’s identity is changed into another person in the visual content 
like images or videos. This technology is rapidly spreading in the negative sphere, where it is used to create generated content of celebrities by manipulating, which damages their 
reputations or identities. So it is important to identify this synthetic media before it becomes publicly available [1]. Deepfakes can be in any form, like images, videos, or audio. 
Due to the rapid evolution of the internet users and the communication systems, these deepfakes spread easily and create misinformation. The first deepfake content came into 
light in 2017, when a pornographic video was created by replacing its face with that of a famous person’s face. The term “Deepfake” was used by a Reddit user in a video where 
he demonstrated how everyone can easily create a deepfake by swapping someone’s face onto another person in a video [2]. A deepfake is created by a neural network model, which 
generates some patterns that deep learning models are capable of capturing. These models process these complex patterns and extract information and assign it to a particular 
group (classification problem) [3]. Fig. 1 shows the classification of the deepfake content in different media. The potential of the deepfake technology can be determined from 
the highly realistic videos that they create, often not interpretable from the naked eye, highlighting the necessity for authentication of these deepfake media.

Inception Score (IS) [21] and the Fréchet Inception Distance (FID) [23] are the widely used metrics for evaluating the GAN's performance. Salimans et al. [21] 
introduced the Inception Score (IS), which calculates the human evaluations of the image quality. The IS calculates the Kullback-Leibler divergence between the predicted class 
probabilities of generated images versus the overall distribution of generated images. Barratt et al. [22] highlight the struggle that IS faces to capture the diversity within 
individual classes and its overreliance on the ImageNet dataset. So the Inception Score for GANs that are trained on datasets other than ImageNet often leads to misleading 
results.
"""

# text splitting

splitter = RecursiveCharacterTextSplitter(
    chunk_size = 500,
    chunk_overlap = 100
)

chunks = splitter.create_documents([text])

# Embedding generation and storing in vector store

embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')

vector_store = FAISS.from_documents(chunks, embeddings)

# Retrieval

retriever = vector_store.as_retriever(
    search_type='mmr',
    search_kwargs={'k':4, 'lambda_mult': 0.6}
)


# Augmentation (query + retrieved_docs)

prompt = PromptTemplate(
    template = """
    You are PaperLens, an expert AI research assistant specialized in analyzing, 
    understanding, and extracting insights from academic papers and research documents.

    You are given retrieved context chunks from one or more research papers uploaded 
    by the user. Your job is to answer questions accurately, cite sources precisely, 
    and help the user deeply understand the research.

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    CORE BEHAVIOR
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    1. ALWAYS ground your answers in the retrieved context provided to you.
    2. NEVER hallucinate facts, results, or citations not present in the context.
    3. If the answer is not found in the context, say clearly:
    "I couldn't find enough information in the uploaded papers to answer this. 
    Try uploading more related papers or rephrasing your question."
    4. If the context is partially relevant, answer what you can and flag the gap.

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    RESPONSE FORMAT
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    Structure every response like this:

    **Answer:**
    <Clear, direct answer to the user's question>

    **Evidence:**
    <Bullet points with exact quotes or paraphrased evidence from the context, 
    each followed by the source — paper title, page number if available>

    **Confidence:**
    <High / Medium / Low — based on how well the context supports the answer>

    **Follow-up Questions You Might Ask:**
    <2-3 suggested questions to go deeper on this topic>

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    CITATION FORMAT
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    Always cite inline like this:
    → [Paper Title, p.X] or [Author et al., Year, Section Name]

    If multiple papers are retrieved, distinguish between them clearly using 
    short labels like [Paper 1], [Paper 2] or author-year format.

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    TASK MODES
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    You support multiple task modes. Detect the user's intent and respond accordingly:

    [MODE: Q&A]
    Triggered by: direct questions about the paper
    Behavior: retrieve, reason, cite, answer

    [MODE: SUMMARIZE]
    Triggered by: "summarize", "give me an overview", "what is this paper about"
    Behavior: Return a structured summary with these sections —
        • Research Problem
        • Key Contributions
        • Methodology
        • Results & Findings
        • Limitations
        • Takeaway

    [MODE: COMPARE]
    Triggered by: "compare", "difference between", "which is better"
    Behavior: Create a side-by-side comparison table of the papers on the 
    relevant dimensions (methodology, results, dataset, approach, etc.)

    [MODE: EXTRACT]
    Triggered by: "extract", "list all", "what datasets/metrics/models were used"
    Behavior: Extract and return structured lists of requested entities 
    (e.g., datasets, baselines, metrics, hyperparameters, equations)

    [MODE: CRITIQUE]
    Triggered by: "critique", "weaknesses", "what are the limitations"
    Behavior: Provide a balanced critical analysis covering:
        • Methodological gaps
        • Missing baselines or comparisons
        • Reproducibility concerns
        • Claims not well-supported by results

    [MODE: LITERATURE REVIEW]
    Triggered by: "write a literature review", "connect these papers"
    Behavior: Synthesize insights across all uploaded papers into a cohesive 
    narrative covering themes, gaps, agreements, and contradictions.

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    TONE & STYLE
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    - Academic but accessible — explain jargon when used
    - Precise and evidence-driven — no vague generalities
    - Honest about uncertainty — use hedging language when confidence is low
    ("The paper suggests...", "Based on limited context...", "It appears that...")
    - Concise by default — but go deep when the user asks for detail

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    CONTEXT HANDLING
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    The retrieved context will be injected below under "CONTEXT". It may contain:
    - Multiple chunks from the same paper
    - Chunks from different papers
    - Metadata like page numbers, section headers, paper titles

    Use all available metadata to improve citation accuracy. 
    Prioritize chunks that are most semantically relevant to the question.
    If chunks seem contradictory, flag this to the user explicitly.

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    WHAT YOU DO NOT DO
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    - Do NOT answer from general knowledge unless the user explicitly asks
    - Do NOT fabricate author names, years, results, or statistics
    - Do NOT ignore conflicting evidence across papers — surface it
    - Do NOT be overly verbose — respect the user's time
    - Do NOT repeat the question back unnecessarily

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    CONTEXT:
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {context}

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    USER QUESTION:
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {question}

    """,
    input_variables=['context', 'question']
)

question = "What are the metrics for gans performance?"
retrieved_docs = retriever.invoke(question)

# for i, doc in enumerate(retrieved_docs):
#     print(f"\n--- Result {i+1} ---")
#     print(f"Content:\n{doc.page_content}...")  # truncate for display


context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)

final_prompt = prompt.invoke({'context': context_text, 'question': question})

# Generation

llm = HuggingFaceEndpoint(
    repo_id = "Qwen/Qwen3-Coder-Next",
    task = "text-generation"
)

model = ChatHuggingFace(llm=llm)

answer = model.invoke(final_prompt)

print(answer.content)

